package tests

import (
	"testing"

	"github.com/httprunner/httprunner/hrp"
)

// generated by examples/data/har/demo.har using HttpRunner v3.1.6
var (
	demoHttpRunnerJSONPath hrp.TestCasePath = "../../examples/hrp/demo_httprunner.json"
	demoHttpRunnerYAMLPath hrp.TestCasePath = "../../examples/hrp/demo_httprunner.yaml"
)

func TestCompatTestCase(t *testing.T) {
	err := hrp.NewRunner(t).Run(&demoHttpRunnerJSONPath)
	if err != nil {
		t.Fatalf("run testcase error: %v", err)
	}

	err = hrp.NewRunner(t).Run(&demoHttpRunnerYAMLPath)
	if err != nil {
		t.Fatalf("run testcase error: %v", err)
	}
}
