# NOTICE: Generated By HttpRunner. DO NOT EDIT!
# FROM: examples/httpbin/upload.yml
from httprunner import HttpRunner, TConfig, TStep


class TestCaseUpload(HttpRunner):
    config = TConfig(
        **{
            "name": "test upload file with httpbin",
            "base_url": "${get_httpbin_server()}",
            "path": "examples/httpbin/upload_test.py",
        }
    )

    teststeps = [
        TStep(
            **{
                "name": "upload file",
                "variables": {
                    "file_path": "test.env",
                    "m_encoder": "${multipart_encoder(file=$file_path)}",
                },
                "request": {
                    "url": "/post",
                    "method": "POST",
                    "headers": {
                        "Content-Type": "${multipart_content_type($m_encoder)}"
                    },
                    "data": "$m_encoder",
                },
                "validate": [
                    {"eq": ["status_code", 200]},
                    {"startswith": ["body.files.file", "UserName=test"]},
                ],
            }
        ),
        TStep(
            **{
                "name": "upload file with keyword",
                "request": {
                    "url": "/post",
                    "method": "POST",
                    "upload": {"file": "test.env"},
                },
                "validate": [
                    {"eq": ["status_code", 200]},
                    {"startswith": ["body.files.file", "UserName=test"]},
                ],
            }
        ),
    ]


if __name__ == "__main__":
    TestCaseUpload().test_start()
