# NOTE: Generated By hrp v4.2.0, DO NOT EDIT!

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from debugtalk import *


if __name__ == "__main__":
    import funppy
    funppy.register("get_httprunner_version", get_httprunner_version)
    funppy.register("sum_two", sum_two)
    funppy.register("get_testcase_config_variables", get_testcase_config_variables)
    funppy.register("get_testsuite_config_variables", get_testsuite_config_variables)
    funppy.register("get_app_version", get_app_version)
    funppy.register("calculate_two_nums", calculate_two_nums)
    funppy.register("fake_rand_count", fake_rand_count)
    funppy.serve()
