# NOTE: Generated By hrp v4.3.6, DO NOT EDIT!

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from debugtalk import *


if __name__ == "__main__":
    import funppy
    funppy.register("ret", ret)
    funppy.register("init_config", init_config)
    funppy.register("get_config_value", get_config_value)
    funppy.register("ENV_VAL", ENV_VAL)
    funppy.register("get_mnt_cookie", get_mnt_cookie)
    funppy.register("get_chartid", get_chartid)
    funppy.register("get_cookie", get_cookie)
    funppy.register("get_meshID", get_meshID)
    funppy.register("get_config_map", get_config_map)
    funppy.register("get_cluster_ip_from_configmap", get_cluster_ip_from_configmap)
    funppy.register("http_compatible_application_values", http_compatible_application_values)
    funppy.register("upd_tcp_app_yml", upd_tcp_app_yml)
    funppy.register("get_host_info", get_host_info)
    funppy.register("get_token", get_token)
    funppy.register("create_namespace", create_namespace)
    funppy.register("del_configmap", del_configmap)
    funppy.register("del_secrets", del_secrets)
    funppy.register("del_namespace", del_namespace)
    funppy.register("get_charts", get_charts)
    funppy.register("get_releases", get_releases)
    funppy.register("del_releases", del_releases)
    funppy.register("del_deployment", del_deployment)
    funppy.register("ns_sidecar_enable", ns_sidecar_enable)
    funppy.register("delete_release", delete_release)
    funppy.register("delete_deployment", delete_deployment)
    funppy.register("wait_delete_namespace", wait_delete_namespace)
    funppy.register("retry_access", retry_access)
    funppy.register("waiting_deployment", waiting_deployment)
    funppy.register("try_http_service", try_http_service)
    funppy.register("now", now)
    funppy.register("init_secret_test_data", init_secret_test_data)
    funppy.register("test_630_tcp_gateway", test_630_tcp_gateway)
    funppy.register("http_route_values", http_route_values)
    funppy.register("http_serviceentry_values", http_serviceentry_values)
    funppy.register("application_values", application_values)
    funppy.register("http_gateway_values", http_gateway_values)
    funppy.register("ingress_values", ingress_values)
    funppy.register("tcp_route_values", tcp_route_values)
    funppy.register("tcp_gateway_values", tcp_gateway_values)
    funppy.register("json_to_yaml", json_to_yaml)
    funppy.register("fetch_chart_info", fetch_chart_info)
    funppy.register("fetch_chart_image", fetch_chart_image)
    funppy.register("send_request_with_retry", send_request_with_retry)
    funppy.serve()
