# NOTE: Generated By HttpRunner v3.1.6
# FROM: request_methods/request_with_fixtures.yml


import debugtalk
import pytest


import allure


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRequestWithFixtures(HttpRunner):
    @allure.title("request with fixture: session fixture")
    def test_start(self, session_fixture):
        scope, fixtures = locals(), ["session_fixture"]
        values = map(lambda x: scope.get(x), fixtures)
        super().test_start(fixtures=dict(zip(fixtures, values)))

    config = Config("request with fixture: session fixture").base_url(
        "https://postman-echo.com"
    )

    teststeps = [
        Step(
            RunRequest("get with params")
            .get("/get")
            .with_params(**{"info": "ip"})
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}/${get_session_fixture($session_fixture)}"
                }
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseRequestWithFixtures().test_start()
