# NOTICE: Generated By HttpRunner. DO'NOT EDIT!
import unittest

from httprunner.runner import TestCaseRunner
from httprunner.schema import TestsConfig, TestStep


class TestCaseRequestWithTestcaseReference(unittest.TestCase):
    config = TestsConfig(
        **{
            "name": "request methods testcase: reference testcase",
            "variables": {"foo1": "session_bar1"},
            "base_url": "https://postman-echo.com",
            "verify": False,
            "path": "examples/postman_echo/request_methods/request_with_testcase_reference_test.py",
        }
    )

    teststeps = [
        TestStep(
            **{
                "name": "request with variables",
                "variables": {"foo1": "override_bar1"},
                "testcase": "request_methods/request_with_variables.yml",
            }
        ),
    ]

    def test_start(self):
        TestCaseRunner(self.config, self.teststeps).run()
