# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_retry.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRequestWithRetry(HttpRunner):

    config = (
        Config("request methods testcase: retry_whens")
        .variables(**{"app_version": "f1"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("get with params")
            .get("/get")
            .with_params(**{"foo4": "${get_num()}"})
            .teardown_hook("${teardown_hook_sleep(1)}")
            .extract()
            .with_jmespath("body.args.foo4", "foo4")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseRequestWithRetry().test_start()
