# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/request_with_retry.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRequestWithRetry(HttpRunner):

    config = (
        Config("request methods testcase: retry_whens")
        .variables(**{"app_version": "f1"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("get with params")
            .get("/get")
            .with_params(**{"foo1": "${get_num()}"})
            .teardown_hook("${teardown_hook_sleep(2)}")
            .extract()
            .with_jmespath("body.args.foo1", "foo1")
            .validate()
            .assert_equal("status_code", 200)
            # .retry_whens()
            # .assert_not_equal("body.args.foo1", "3")
        ),
    ]


if __name__ == "__main__":
    TestCaseRequestWithRetry().test_start()
