# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/testcase_with_retry.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.request_with_retry_test import (
    TestCaseRequestWithRetry as RequestWithRetry,
)


class TestCaseTestcaseWithRetry(HttpRunner):

    config = (
        Config("request methods testcase: retry_whens")
        .variables(**{"app_version": "f1"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunTestCase("request with retry")
            .call(RequestWithRetry)
            .export(*["foo1"])
            .retry_whens()
            .assert_not_equal("$foo1", 3)
        ),
    ]


if __name__ == "__main__":
    TestCaseTestcaseWithRetry().test_start()
