name: Deploy docs to GitHub Pages

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    name: Deploy docs to GitHub Pages
    if: ${{ github.event.pull_request.merged }} # true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python3 env
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs and material design
        run: pip install mkdocs-material  # including mkdocs
      - name: Update hrp cli docs
        run: go test docs/cmd/doc_test.go # update hrp cli docs
      - name: Deploy docs to github pages
        run: mkdocs gh-deploy --force
